### ISSUE TITLE
how to include?

### ISSUE THREAD

**Issue by heaversm** [mapbox/geojson-random#10]
Hi - would love to use this, but I wasn't sure how to get it going in a standard implementation of mapboxjs without adding requirejs(?) / node / etc. Is that possible?

**Comment by tmcw** [comment]
You can use [browserify cdn](https://www.brcdn.org/) for this purpose: type in `geojson-random`, and download a standalone build. Then you'll have a javascript file that exposes `geojsonRandom` on the page.

**Comment by heaversm** [comment]
Thanks - this was really useful - never knew there was a utility for generating browserified node modules (and I forgot all about browserify...)
