### ISSUE TITLE
polygon

### ISSUE THREAD

**Issue by tmcw** [mapbox/geojson-random#2]
like linestring, would be great if it fit the simple features spec and was non-self-intersecting, but that's a nice-to-have.

**Comment by tmcw** [comment]
:+1:

**Comment by allthesignals** [comment]
Thank you for creating this, just a quick question on this issue: do you know if random polygon safely generates non-self-intersecting? I'm doing some automated testing with random geometries, and I've had some trouble with [turf's solution](https://github.com/Turfjs/turf/tree/master/packages/turf-random) generating invalid geometries. 

Thanks!
